## Отчет по первой части

In [1]:
from methods import *

x = np.array([5, 5, 5])
gesse = np.array([
    [
        finite_difference2(x, np.array((1, 0, 0)), np.array((1, 0, 0))),
        finite_difference2(x, np.array((1, 0, 0)), np.array((0, 1, 0))),
        finite_difference2(x, np.array((1, 0, 0)), np.array((0, 0, 1)))
    ],
    [
        finite_difference2(x, np.array((0, 1, 0)), np.array((1, 0, 0))),
        finite_difference2(x, np.array((0, 1, 0)), np.array((0, 1, 0))),
        finite_difference2(x, np.array((0, 1, 0)), np.array((0, 0, 1)))
    ],
    [
        finite_difference2(x, np.array((0, 0, 1)), np.array((1, 0, 0))),
        finite_difference2(x, np.array((0, 0, 1)), np.array((0, 1, 0))),
        finite_difference2(x, np.array((0, 0, 1)), np.array((0, 0, 1)))
    ]
])

In [2]:
epsilon = 1e-4
c1 = 0.0001
c2 = 0.9
a_max = 1
max_iter = 10000
search_max_iter = 100
mem_limit = 10
initial_gesse = np.eye(3)
analitic_gesse = np.array([
    [0.75, 0.5, 0.25],
    [0.5, 1, 0.5],
    [0.25, 0.5, 0.75]
])

In [3]:

print("Task 1.1")
print("Алгоритмы BFGS и L-BFGS применимы к этой задаче, так как функция f(x) является дважды дифференцируемой выпуклой функцией.")
print()
print("Task 1.2")

point, iter = bfgs(f, g, initial_gesse, x, epsilon, c1, c2, a_max, max_iter, search_max_iter)
print(f'BFGS (a) x={point}, f(x)={f(point)} iter={iter}')

point, iter = bfgs(f, numerical_g, initial_gesse, x, epsilon, c1, c2, a_max, max_iter, search_max_iter)
print(f'BFGS (b) x={point}, f(x)={f(point)} iter={iter}')

point, iter = lbfgs(g, initial_gesse, x, epsilon, max_iter, mem_limit)
print(f'L-BFGS (a) x={point}, f(x)={f(point)} iter={iter}')

point, iter = lbfgs(numerical_g, initial_gesse, x, epsilon, max_iter, mem_limit)
print(f'L-BFGS (b) x={point}, f(x)={f(point)} iter={iter}')
print()
print("Task 1.3")
print("Approximate Gesse matrix")
print(gesse)
point, iter = bfgs(f, g, gesse, x, epsilon, c1, c2, a_max, max_iter, search_max_iter)
print(f'BFGS x={point}, f(x)={f(point)} iter={iter}')
print()
print("Analitic Gesse matrix")
print(analitic_gesse)
point, iter = bfgs(f, g, analitic_gesse, x, epsilon, c1, c2, a_max, max_iter, search_max_iter)
print(f'BFGS x={point}, f(x)={f(point)} iter={iter}')
print()


Task 1.1
Алгоритмы BFGS и L-BFGS применимы к этой задаче, так как функция f(x) является дважды дифференцируемой выпуклой функцией.

Task 1.2
BFGS (a) x=[0.7500026  0.49999919 0.25000293], f(x)=-0.3749999999794626 iter=7
BFGS (b) x=[0.7500026  0.49999919 0.25000293], f(x)=-0.3749999999794626 iter=7
L-BFGS (a) x=[0.75000832 0.49999473 0.2500365 ], f(x)=-0.3749999983346668 iter=7
L-BFGS (b) x=[0.75000832 0.49999473 0.2500365 ], f(x)=-0.3749999983346668 iter=7

Task 1.3
Approximate Gesse matrix
[[ 4. -2.  0.]
 [-2.  4. -2.]
 [ 0. -2.  4.]]
BFGS x=[0.74996431 0.499974   0.24996614], f(x)=-0.3749999987116779 iter=8

Analitic Gesse matrix
[[0.75 0.5  0.25]
 [0.5  1.   0.5 ]
 [0.25 0.5  0.75]]
BFGS x=[0.75 0.5  0.25], f(x)=-0.375 iter=1

